apiVersion: v1
kind: Namespace
metadata:
  name: pentest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forestgump-sa
  namespace: pentest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forestgump-role
  namespace: pentest
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forestgump-bind
  namespace: pentest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forestgump-role
subjects:
  - kind: ServiceAccount
    name: forestgump-sa
    namespace: pentest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forestgump
  namespace: pentest
  labels:
    app: forestgump
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forestgump
  template:
    metadata:
      labels:
        app: forestgump
    spec:
      serviceAccountName: forestgump-sa
      containers:
        - name: forestgump
          image: ghcr.io/benjitrapp/forestgump.sh:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7681
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: forestgump
  namespace: pentest
  labels:
    app: forestgump
spec:
  type: LoadBalancer
  ports:
    - port: 7681
      targetPort: 7681
      protocol: TCP
  selector:
    app: forestgump
