#!/bin/bash
# ForestGump.sh - AD Attack Platform
# Launches ttyd on port 7681 for browser-based terminal access

echo "============================================"
echo "  ForestGump.sh - AD Attack Platform"
echo "============================================"
echo ""
echo "Available tools:"
echo ""
echo "  [ AD RECON & ENUM ]"
echo "    bloodhound-python  - BloodHound Python ingestor"
echo "    nxc                - NetExec (SMB/LDAP/WinRM/MS-SQL)"
echo "    ldapdomaindump     - LDAP domain dumper"
echo "    ad-reaper          - Multi-protocol AD enumerator"
echo "    godap              - LDAP TUI explorer"
echo "    ldapnomnom         - Anonymous LDAP username bruteforce"
echo "    Responder          - LLMNR/NBT-NS/MDNS poisoner"
echo "    snafflepy          - Interesting file discovery (SMB)"
echo "    gpohunter          - GPO misconfiguration analyzer"
echo "    gpoParser          - GPO extraction & analysis"
echo "    nmap / dig / nsl   - Network scanners"
echo ""
echo "  [ AUTH ATTACKS & RELAY ]"
echo "    impacket           - Full Impacket suite"
echo "    coercer            - Auto Windows auth coercion"
echo "    relayking          - NTLM/Kerberos relay detection"
echo "    gontlm-proxy       - NTLM proxy forwarder"
echo "    px                 - NTLM proxy (Python)"
echo ""
echo "  [ PRIV ESC & EXPLOIT ]"
echo "    bloodyAD           - AD privilege escalation"
echo "    certipy-ad         - ADCS abuse toolkit"
echo "    pysidhistory       - Remote SID History injection"
echo "    getspnless         - SPN-less RBCD attacks"
echo "    donpapi            - Remote DPAPI credential dumper"
echo "    mimikatz / Rubeus  - Windows credential abuse"
echo ""
echo "  [ CLOUD (ENTRA ID / AZURE) ]"
echo "    roadrecon / roadtx - ROADtools (Entra ID exploration)"
echo "    entrafalcon        - Entra ID enumeration (PowerShell)"
echo "    ca-insight         - Conditional Access gap analysis"
echo "    tokensmith         - Entra ID token generator"
echo "    graphspy           - Entra ID/M365 post-exploitation GUI (port 5000)"
echo "    credspy            - Entra ID user enum & auth method discovery"
echo "    o365creeper        - O365 email validation (no login attempts)"
echo "    tokentactics       - Azure JWT token manipulation (PowerShell)"
echo ""
echo "  [ SHELLS & REMOTE ]"
echo "    evil-winrm         - WinRM shell (Ruby)"
echo "    xfreerdp           - RDP client (headless-safe)"
echo "    rdp-browser        - Browser-accessible RDP via noVNC"
echo "    tightvncserver     - VNC server"
echo "    pwsh               - PowerShell 7"
echo ""
echo "  [ UTILITY ]"
echo "    gopacket           - Go Impacket (63 tools)"
echo "    AdStrike           - AI-powered AD red-team framework"
echo "    PowerSploit        - PowerView, PowerUp, etc."
echo ""
echo "Access the terminal at http://localhost:7681"
echo "============================================"
echo ""

exec ttyd -W -p 7681 /opt/scripts/shell.sh
